/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MailRouteImport } from './routes/mail'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as CronjobsRouteImport } from './routes/cronjobs'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MailIndexRouteImport } from './routes/mail/index'
import { Route as KnowledgeBaseIndexRouteImport } from './routes/knowledge-base/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as CronjobsIndexRouteImport } from './routes/cronjobs/index'
import { Route as ConversationsIndexRouteImport } from './routes/conversations/index'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as JobsExtractFromUrlRouteImport } from './routes/jobs/extract-from-url'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as CronjobsNewRouteImport } from './routes/cronjobs/new'
import { Route as CronjobsIdRouteImport } from './routes/cronjobs/$id'
import { Route as ConversationsNewRouteImport } from './routes/conversations/new'
import { Route as ConversationsIdRouteImport } from './routes/conversations/$id'
import { Route as ApiSectionsRouteImport } from './routes/api/sections'
import { Route as ApiChatSyncRouteImport } from './routes/api/chat-sync'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CronjobsIdIndexRouteImport } from './routes/cronjobs/$id/index'
import { Route as ApiKnowledgeBaseIndexRouteImport } from './routes/api/knowledge-base/index'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiGeneratedFilesIndexRouteImport } from './routes/api/generated-files/index'
import { Route as ApiCronjobsIndexRouteImport } from './routes/api/cronjobs/index'
import { Route as ApiConversationsIndexRouteImport } from './routes/api/conversations/index'
import { Route as CronjobsIdLogsRouteImport } from './routes/cronjobs/$id/logs'
import { Route as ApiReportsScrapeJobsRouteImport } from './routes/api/reports/scrape-jobs'
import { Route as ApiMailStoreEmailsRouteImport } from './routes/api/mail/store-emails'
import { Route as ApiMailIngestRouteImport } from './routes/api/mail/ingest'
import { Route as ApiMailEmailsByJobRouteImport } from './routes/api/mail/emails-by-job'
import { Route as ApiMailEmailsRouteImport } from './routes/api/mail/emails'
import { Route as ApiMailEmailCountRouteImport } from './routes/api/mail/email-count'
import { Route as ApiMailAllRouteImport } from './routes/api/mail/all'
import { Route as ApiMailIdRouteImport } from './routes/api/mail/$id'
import { Route as ApiKnowledgeBaseIdRouteImport } from './routes/api/knowledge-base/$id'
import { Route as ApiJobsProcessRouteImport } from './routes/api/jobs/process'
import { Route as ApiJobsGenerateResumeRouteImport } from './routes/api/jobs/generate-resume'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiGeneratedFilesIdRouteImport } from './routes/api/generated-files/$id'
import { Route as ApiFilesFilenameRouteImport } from './routes/api/files/$filename'
import { Route as ApiCronjobsIdRouteImport } from './routes/api/cronjobs/$id'
import { Route as ApiConversationsIdRouteImport } from './routes/api/conversations/$id'
import { Route as ApiCronjobsIdTestRouteImport } from './routes/api/cronjobs/$id/test'
import { Route as ApiCronjobsIdLogsRouteImport } from './routes/api/cronjobs/$id/logs'

const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CronjobsRoute = CronjobsRouteImport.update({
  id: '/cronjobs',
  path: '/cronjobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailIndexRoute = MailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MailRoute,
} as any)
const KnowledgeBaseIndexRoute = KnowledgeBaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeBaseRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const CronjobsIndexRoute = CronjobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CronjobsRoute,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConversationsRoute,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JobsRoute,
} as any)
const JobsExtractFromUrlRoute = JobsExtractFromUrlRouteImport.update({
  id: '/extract-from-url',
  path: '/extract-from-url',
  getParentRoute: () => JobsRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const CronjobsNewRoute = CronjobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CronjobsRoute,
} as any)
const CronjobsIdRoute = CronjobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CronjobsRoute,
} as any)
const ConversationsNewRoute = ConversationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConversationsRoute,
} as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConversationsRoute,
} as any)
const ApiSectionsRoute = ApiSectionsRouteImport.update({
  id: '/api/sections',
  path: '/api/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSyncRoute = ApiChatSyncRouteImport.update({
  id: '/api/chat-sync',
  path: '/api/chat-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CronjobsIdIndexRoute = CronjobsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CronjobsIdRoute,
} as any)
const ApiKnowledgeBaseIndexRoute = ApiKnowledgeBaseIndexRouteImport.update({
  id: '/api/knowledge-base/',
  path: '/api/knowledge-base/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratedFilesIndexRoute = ApiGeneratedFilesIndexRouteImport.update({
  id: '/api/generated-files/',
  path: '/api/generated-files/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronjobsIndexRoute = ApiCronjobsIndexRouteImport.update({
  id: '/api/cronjobs/',
  path: '/api/cronjobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIndexRoute = ApiConversationsIndexRouteImport.update({
  id: '/api/conversations/',
  path: '/api/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CronjobsIdLogsRoute = CronjobsIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => CronjobsIdRoute,
} as any)
const ApiReportsScrapeJobsRoute = ApiReportsScrapeJobsRouteImport.update({
  id: '/api/reports/scrape-jobs',
  path: '/api/reports/scrape-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailStoreEmailsRoute = ApiMailStoreEmailsRouteImport.update({
  id: '/api/mail/store-emails',
  path: '/api/mail/store-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailIngestRoute = ApiMailIngestRouteImport.update({
  id: '/api/mail/ingest',
  path: '/api/mail/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailEmailsByJobRoute = ApiMailEmailsByJobRouteImport.update({
  id: '/api/mail/emails-by-job',
  path: '/api/mail/emails-by-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailEmailsRoute = ApiMailEmailsRouteImport.update({
  id: '/api/mail/emails',
  path: '/api/mail/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailEmailCountRoute = ApiMailEmailCountRouteImport.update({
  id: '/api/mail/email-count',
  path: '/api/mail/email-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailAllRoute = ApiMailAllRouteImport.update({
  id: '/api/mail/all',
  path: '/api/mail/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailIdRoute = ApiMailIdRouteImport.update({
  id: '/api/mail/$id',
  path: '/api/mail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeBaseIdRoute = ApiKnowledgeBaseIdRouteImport.update({
  id: '/api/knowledge-base/$id',
  path: '/api/knowledge-base/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsProcessRoute = ApiJobsProcessRouteImport.update({
  id: '/api/jobs/process',
  path: '/api/jobs/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsGenerateResumeRoute = ApiJobsGenerateResumeRouteImport.update({
  id: '/api/jobs/generate-resume',
  path: '/api/jobs/generate-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratedFilesIdRoute = ApiGeneratedFilesIdRouteImport.update({
  id: '/api/generated-files/$id',
  path: '/api/generated-files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesFilenameRoute = ApiFilesFilenameRouteImport.update({
  id: '/api/files/$filename',
  path: '/api/files/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronjobsIdRoute = ApiCronjobsIdRouteImport.update({
  id: '/api/cronjobs/$id',
  path: '/api/cronjobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdRoute = ApiConversationsIdRouteImport.update({
  id: '/api/conversations/$id',
  path: '/api/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronjobsIdTestRoute = ApiCronjobsIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiCronjobsIdRoute,
} as any)
const ApiCronjobsIdLogsRoute = ApiCronjobsIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ApiCronjobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/cronjobs': typeof CronjobsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/knowledge-base': typeof KnowledgeBaseRouteWithChildren
  '/mail': typeof MailRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/chat-sync': typeof ApiChatSyncRoute
  '/api/sections': typeof ApiSectionsRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/cronjobs/$id': typeof CronjobsIdRouteWithChildren
  '/cronjobs/new': typeof CronjobsNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/extract-from-url': typeof JobsExtractFromUrlRoute
  '/jobs/new': typeof JobsNewRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/cronjobs/': typeof CronjobsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
  '/mail/': typeof MailIndexRoute
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/cronjobs/$id': typeof ApiCronjobsIdRouteWithChildren
  '/api/files/$filename': typeof ApiFilesFilenameRoute
  '/api/generated-files/$id': typeof ApiGeneratedFilesIdRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/generate-resume': typeof ApiJobsGenerateResumeRoute
  '/api/jobs/process': typeof ApiJobsProcessRoute
  '/api/knowledge-base/$id': typeof ApiKnowledgeBaseIdRoute
  '/api/mail/$id': typeof ApiMailIdRoute
  '/api/mail/all': typeof ApiMailAllRoute
  '/api/mail/email-count': typeof ApiMailEmailCountRoute
  '/api/mail/emails': typeof ApiMailEmailsRoute
  '/api/mail/emails-by-job': typeof ApiMailEmailsByJobRoute
  '/api/mail/ingest': typeof ApiMailIngestRoute
  '/api/mail/store-emails': typeof ApiMailStoreEmailsRoute
  '/api/reports/scrape-jobs': typeof ApiReportsScrapeJobsRoute
  '/cronjobs/$id/logs': typeof CronjobsIdLogsRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/cronjobs/': typeof ApiCronjobsIndexRoute
  '/api/generated-files/': typeof ApiGeneratedFilesIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/knowledge-base/': typeof ApiKnowledgeBaseIndexRoute
  '/cronjobs/$id/': typeof CronjobsIdIndexRoute
  '/api/cronjobs/$id/logs': typeof ApiCronjobsIdLogsRoute
  '/api/cronjobs/$id/test': typeof ApiCronjobsIdTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-sync': typeof ApiChatSyncRoute
  '/api/sections': typeof ApiSectionsRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/cronjobs/new': typeof CronjobsNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/extract-from-url': typeof JobsExtractFromUrlRoute
  '/jobs/new': typeof JobsNewRoute
  '/conversations': typeof ConversationsIndexRoute
  '/cronjobs': typeof CronjobsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/knowledge-base': typeof KnowledgeBaseIndexRoute
  '/mail': typeof MailIndexRoute
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/cronjobs/$id': typeof ApiCronjobsIdRouteWithChildren
  '/api/files/$filename': typeof ApiFilesFilenameRoute
  '/api/generated-files/$id': typeof ApiGeneratedFilesIdRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/generate-resume': typeof ApiJobsGenerateResumeRoute
  '/api/jobs/process': typeof ApiJobsProcessRoute
  '/api/knowledge-base/$id': typeof ApiKnowledgeBaseIdRoute
  '/api/mail/$id': typeof ApiMailIdRoute
  '/api/mail/all': typeof ApiMailAllRoute
  '/api/mail/email-count': typeof ApiMailEmailCountRoute
  '/api/mail/emails': typeof ApiMailEmailsRoute
  '/api/mail/emails-by-job': typeof ApiMailEmailsByJobRoute
  '/api/mail/ingest': typeof ApiMailIngestRoute
  '/api/mail/store-emails': typeof ApiMailStoreEmailsRoute
  '/api/reports/scrape-jobs': typeof ApiReportsScrapeJobsRoute
  '/cronjobs/$id/logs': typeof CronjobsIdLogsRoute
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/cronjobs': typeof ApiCronjobsIndexRoute
  '/api/generated-files': typeof ApiGeneratedFilesIndexRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/knowledge-base': typeof ApiKnowledgeBaseIndexRoute
  '/cronjobs/$id': typeof CronjobsIdIndexRoute
  '/api/cronjobs/$id/logs': typeof ApiCronjobsIdLogsRoute
  '/api/cronjobs/$id/test': typeof ApiCronjobsIdTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRouteWithChildren
  '/cronjobs': typeof CronjobsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/knowledge-base': typeof KnowledgeBaseRouteWithChildren
  '/mail': typeof MailRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/chat-sync': typeof ApiChatSyncRoute
  '/api/sections': typeof ApiSectionsRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/conversations/new': typeof ConversationsNewRoute
  '/cronjobs/$id': typeof CronjobsIdRouteWithChildren
  '/cronjobs/new': typeof CronjobsNewRoute
  '/jobs/$id': typeof JobsIdRoute
  '/jobs/extract-from-url': typeof JobsExtractFromUrlRoute
  '/jobs/new': typeof JobsNewRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/cronjobs/': typeof CronjobsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
  '/mail/': typeof MailIndexRoute
  '/api/conversations/$id': typeof ApiConversationsIdRoute
  '/api/cronjobs/$id': typeof ApiCronjobsIdRouteWithChildren
  '/api/files/$filename': typeof ApiFilesFilenameRoute
  '/api/generated-files/$id': typeof ApiGeneratedFilesIdRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/jobs/generate-resume': typeof ApiJobsGenerateResumeRoute
  '/api/jobs/process': typeof ApiJobsProcessRoute
  '/api/knowledge-base/$id': typeof ApiKnowledgeBaseIdRoute
  '/api/mail/$id': typeof ApiMailIdRoute
  '/api/mail/all': typeof ApiMailAllRoute
  '/api/mail/email-count': typeof ApiMailEmailCountRoute
  '/api/mail/emails': typeof ApiMailEmailsRoute
  '/api/mail/emails-by-job': typeof ApiMailEmailsByJobRoute
  '/api/mail/ingest': typeof ApiMailIngestRoute
  '/api/mail/store-emails': typeof ApiMailStoreEmailsRoute
  '/api/reports/scrape-jobs': typeof ApiReportsScrapeJobsRoute
  '/cronjobs/$id/logs': typeof CronjobsIdLogsRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/cronjobs/': typeof ApiCronjobsIndexRoute
  '/api/generated-files/': typeof ApiGeneratedFilesIndexRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/knowledge-base/': typeof ApiKnowledgeBaseIndexRoute
  '/cronjobs/$id/': typeof CronjobsIdIndexRoute
  '/api/cronjobs/$id/logs': typeof ApiCronjobsIdLogsRoute
  '/api/cronjobs/$id/test': typeof ApiCronjobsIdTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/cronjobs'
    | '/jobs'
    | '/knowledge-base'
    | '/mail'
    | '/api/chat'
    | '/api/chat-sync'
    | '/api/sections'
    | '/conversations/$id'
    | '/conversations/new'
    | '/cronjobs/$id'
    | '/cronjobs/new'
    | '/jobs/$id'
    | '/jobs/extract-from-url'
    | '/jobs/new'
    | '/conversations/'
    | '/cronjobs/'
    | '/jobs/'
    | '/knowledge-base/'
    | '/mail/'
    | '/api/conversations/$id'
    | '/api/cronjobs/$id'
    | '/api/files/$filename'
    | '/api/generated-files/$id'
    | '/api/jobs/$id'
    | '/api/jobs/generate-resume'
    | '/api/jobs/process'
    | '/api/knowledge-base/$id'
    | '/api/mail/$id'
    | '/api/mail/all'
    | '/api/mail/email-count'
    | '/api/mail/emails'
    | '/api/mail/emails-by-job'
    | '/api/mail/ingest'
    | '/api/mail/store-emails'
    | '/api/reports/scrape-jobs'
    | '/cronjobs/$id/logs'
    | '/api/conversations/'
    | '/api/cronjobs/'
    | '/api/generated-files/'
    | '/api/jobs/'
    | '/api/knowledge-base/'
    | '/cronjobs/$id/'
    | '/api/cronjobs/$id/logs'
    | '/api/cronjobs/$id/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/chat-sync'
    | '/api/sections'
    | '/conversations/$id'
    | '/conversations/new'
    | '/cronjobs/new'
    | '/jobs/$id'
    | '/jobs/extract-from-url'
    | '/jobs/new'
    | '/conversations'
    | '/cronjobs'
    | '/jobs'
    | '/knowledge-base'
    | '/mail'
    | '/api/conversations/$id'
    | '/api/cronjobs/$id'
    | '/api/files/$filename'
    | '/api/generated-files/$id'
    | '/api/jobs/$id'
    | '/api/jobs/generate-resume'
    | '/api/jobs/process'
    | '/api/knowledge-base/$id'
    | '/api/mail/$id'
    | '/api/mail/all'
    | '/api/mail/email-count'
    | '/api/mail/emails'
    | '/api/mail/emails-by-job'
    | '/api/mail/ingest'
    | '/api/mail/store-emails'
    | '/api/reports/scrape-jobs'
    | '/cronjobs/$id/logs'
    | '/api/conversations'
    | '/api/cronjobs'
    | '/api/generated-files'
    | '/api/jobs'
    | '/api/knowledge-base'
    | '/cronjobs/$id'
    | '/api/cronjobs/$id/logs'
    | '/api/cronjobs/$id/test'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/cronjobs'
    | '/jobs'
    | '/knowledge-base'
    | '/mail'
    | '/api/chat'
    | '/api/chat-sync'
    | '/api/sections'
    | '/conversations/$id'
    | '/conversations/new'
    | '/cronjobs/$id'
    | '/cronjobs/new'
    | '/jobs/$id'
    | '/jobs/extract-from-url'
    | '/jobs/new'
    | '/conversations/'
    | '/cronjobs/'
    | '/jobs/'
    | '/knowledge-base/'
    | '/mail/'
    | '/api/conversations/$id'
    | '/api/cronjobs/$id'
    | '/api/files/$filename'
    | '/api/generated-files/$id'
    | '/api/jobs/$id'
    | '/api/jobs/generate-resume'
    | '/api/jobs/process'
    | '/api/knowledge-base/$id'
    | '/api/mail/$id'
    | '/api/mail/all'
    | '/api/mail/email-count'
    | '/api/mail/emails'
    | '/api/mail/emails-by-job'
    | '/api/mail/ingest'
    | '/api/mail/store-emails'
    | '/api/reports/scrape-jobs'
    | '/cronjobs/$id/logs'
    | '/api/conversations/'
    | '/api/cronjobs/'
    | '/api/generated-files/'
    | '/api/jobs/'
    | '/api/knowledge-base/'
    | '/cronjobs/$id/'
    | '/api/cronjobs/$id/logs'
    | '/api/cronjobs/$id/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRouteWithChildren
  CronjobsRoute: typeof CronjobsRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  KnowledgeBaseRoute: typeof KnowledgeBaseRouteWithChildren
  MailRoute: typeof MailRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiChatSyncRoute: typeof ApiChatSyncRoute
  ApiSectionsRoute: typeof ApiSectionsRoute
  ApiConversationsIdRoute: typeof ApiConversationsIdRoute
  ApiCronjobsIdRoute: typeof ApiCronjobsIdRouteWithChildren
  ApiFilesFilenameRoute: typeof ApiFilesFilenameRoute
  ApiGeneratedFilesIdRoute: typeof ApiGeneratedFilesIdRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiJobsGenerateResumeRoute: typeof ApiJobsGenerateResumeRoute
  ApiJobsProcessRoute: typeof ApiJobsProcessRoute
  ApiKnowledgeBaseIdRoute: typeof ApiKnowledgeBaseIdRoute
  ApiMailIdRoute: typeof ApiMailIdRoute
  ApiMailAllRoute: typeof ApiMailAllRoute
  ApiMailEmailCountRoute: typeof ApiMailEmailCountRoute
  ApiMailEmailsRoute: typeof ApiMailEmailsRoute
  ApiMailEmailsByJobRoute: typeof ApiMailEmailsByJobRoute
  ApiMailIngestRoute: typeof ApiMailIngestRoute
  ApiMailStoreEmailsRoute: typeof ApiMailStoreEmailsRoute
  ApiReportsScrapeJobsRoute: typeof ApiReportsScrapeJobsRoute
  ApiConversationsIndexRoute: typeof ApiConversationsIndexRoute
  ApiCronjobsIndexRoute: typeof ApiCronjobsIndexRoute
  ApiGeneratedFilesIndexRoute: typeof ApiGeneratedFilesIndexRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiKnowledgeBaseIndexRoute: typeof ApiKnowledgeBaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronjobs': {
      id: '/cronjobs'
      path: '/cronjobs'
      fullPath: '/cronjobs'
      preLoaderRoute: typeof CronjobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail/': {
      id: '/mail/'
      path: '/'
      fullPath: '/mail/'
      preLoaderRoute: typeof MailIndexRouteImport
      parentRoute: typeof MailRoute
    }
    '/knowledge-base/': {
      id: '/knowledge-base/'
      path: '/'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof KnowledgeBaseIndexRouteImport
      parentRoute: typeof KnowledgeBaseRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/cronjobs/': {
      id: '/cronjobs/'
      path: '/'
      fullPath: '/cronjobs/'
      preLoaderRoute: typeof CronjobsIndexRouteImport
      parentRoute: typeof CronjobsRoute
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/extract-from-url': {
      id: '/jobs/extract-from-url'
      path: '/extract-from-url'
      fullPath: '/jobs/extract-from-url'
      preLoaderRoute: typeof JobsExtractFromUrlRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/cronjobs/new': {
      id: '/cronjobs/new'
      path: '/new'
      fullPath: '/cronjobs/new'
      preLoaderRoute: typeof CronjobsNewRouteImport
      parentRoute: typeof CronjobsRoute
    }
    '/cronjobs/$id': {
      id: '/cronjobs/$id'
      path: '/$id'
      fullPath: '/cronjobs/$id'
      preLoaderRoute: typeof CronjobsIdRouteImport
      parentRoute: typeof CronjobsRoute
    }
    '/conversations/new': {
      id: '/conversations/new'
      path: '/new'
      fullPath: '/conversations/new'
      preLoaderRoute: typeof ConversationsNewRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof ConversationsRoute
    }
    '/api/sections': {
      id: '/api/sections'
      path: '/api/sections'
      fullPath: '/api/sections'
      preLoaderRoute: typeof ApiSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-sync': {
      id: '/api/chat-sync'
      path: '/api/chat-sync'
      fullPath: '/api/chat-sync'
      preLoaderRoute: typeof ApiChatSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronjobs/$id/': {
      id: '/cronjobs/$id/'
      path: '/'
      fullPath: '/cronjobs/$id/'
      preLoaderRoute: typeof CronjobsIdIndexRouteImport
      parentRoute: typeof CronjobsIdRoute
    }
    '/api/knowledge-base/': {
      id: '/api/knowledge-base/'
      path: '/api/knowledge-base'
      fullPath: '/api/knowledge-base/'
      preLoaderRoute: typeof ApiKnowledgeBaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generated-files/': {
      id: '/api/generated-files/'
      path: '/api/generated-files'
      fullPath: '/api/generated-files/'
      preLoaderRoute: typeof ApiGeneratedFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cronjobs/': {
      id: '/api/cronjobs/'
      path: '/api/cronjobs'
      fullPath: '/api/cronjobs/'
      preLoaderRoute: typeof ApiCronjobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/': {
      id: '/api/conversations/'
      path: '/api/conversations'
      fullPath: '/api/conversations/'
      preLoaderRoute: typeof ApiConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronjobs/$id/logs': {
      id: '/cronjobs/$id/logs'
      path: '/logs'
      fullPath: '/cronjobs/$id/logs'
      preLoaderRoute: typeof CronjobsIdLogsRouteImport
      parentRoute: typeof CronjobsIdRoute
    }
    '/api/reports/scrape-jobs': {
      id: '/api/reports/scrape-jobs'
      path: '/api/reports/scrape-jobs'
      fullPath: '/api/reports/scrape-jobs'
      preLoaderRoute: typeof ApiReportsScrapeJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/store-emails': {
      id: '/api/mail/store-emails'
      path: '/api/mail/store-emails'
      fullPath: '/api/mail/store-emails'
      preLoaderRoute: typeof ApiMailStoreEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/ingest': {
      id: '/api/mail/ingest'
      path: '/api/mail/ingest'
      fullPath: '/api/mail/ingest'
      preLoaderRoute: typeof ApiMailIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/emails-by-job': {
      id: '/api/mail/emails-by-job'
      path: '/api/mail/emails-by-job'
      fullPath: '/api/mail/emails-by-job'
      preLoaderRoute: typeof ApiMailEmailsByJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/emails': {
      id: '/api/mail/emails'
      path: '/api/mail/emails'
      fullPath: '/api/mail/emails'
      preLoaderRoute: typeof ApiMailEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/email-count': {
      id: '/api/mail/email-count'
      path: '/api/mail/email-count'
      fullPath: '/api/mail/email-count'
      preLoaderRoute: typeof ApiMailEmailCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/all': {
      id: '/api/mail/all'
      path: '/api/mail/all'
      fullPath: '/api/mail/all'
      preLoaderRoute: typeof ApiMailAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/$id': {
      id: '/api/mail/$id'
      path: '/api/mail/$id'
      fullPath: '/api/mail/$id'
      preLoaderRoute: typeof ApiMailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge-base/$id': {
      id: '/api/knowledge-base/$id'
      path: '/api/knowledge-base/$id'
      fullPath: '/api/knowledge-base/$id'
      preLoaderRoute: typeof ApiKnowledgeBaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/process': {
      id: '/api/jobs/process'
      path: '/api/jobs/process'
      fullPath: '/api/jobs/process'
      preLoaderRoute: typeof ApiJobsProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/generate-resume': {
      id: '/api/jobs/generate-resume'
      path: '/api/jobs/generate-resume'
      fullPath: '/api/jobs/generate-resume'
      preLoaderRoute: typeof ApiJobsGenerateResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generated-files/$id': {
      id: '/api/generated-files/$id'
      path: '/api/generated-files/$id'
      fullPath: '/api/generated-files/$id'
      preLoaderRoute: typeof ApiGeneratedFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$filename': {
      id: '/api/files/$filename'
      path: '/api/files/$filename'
      fullPath: '/api/files/$filename'
      preLoaderRoute: typeof ApiFilesFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cronjobs/$id': {
      id: '/api/cronjobs/$id'
      path: '/api/cronjobs/$id'
      fullPath: '/api/cronjobs/$id'
      preLoaderRoute: typeof ApiCronjobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id': {
      id: '/api/conversations/$id'
      path: '/api/conversations/$id'
      fullPath: '/api/conversations/$id'
      preLoaderRoute: typeof ApiConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cronjobs/$id/test': {
      id: '/api/cronjobs/$id/test'
      path: '/test'
      fullPath: '/api/cronjobs/$id/test'
      preLoaderRoute: typeof ApiCronjobsIdTestRouteImport
      parentRoute: typeof ApiCronjobsIdRoute
    }
    '/api/cronjobs/$id/logs': {
      id: '/api/cronjobs/$id/logs'
      path: '/logs'
      fullPath: '/api/cronjobs/$id/logs'
      preLoaderRoute: typeof ApiCronjobsIdLogsRouteImport
      parentRoute: typeof ApiCronjobsIdRoute
    }
  }
}

interface ConversationsRouteChildren {
  ConversationsIdRoute: typeof ConversationsIdRoute
  ConversationsNewRoute: typeof ConversationsNewRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
}

const ConversationsRouteChildren: ConversationsRouteChildren = {
  ConversationsIdRoute: ConversationsIdRoute,
  ConversationsNewRoute: ConversationsNewRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
}

const ConversationsRouteWithChildren = ConversationsRoute._addFileChildren(
  ConversationsRouteChildren,
)

interface CronjobsIdRouteChildren {
  CronjobsIdLogsRoute: typeof CronjobsIdLogsRoute
  CronjobsIdIndexRoute: typeof CronjobsIdIndexRoute
}

const CronjobsIdRouteChildren: CronjobsIdRouteChildren = {
  CronjobsIdLogsRoute: CronjobsIdLogsRoute,
  CronjobsIdIndexRoute: CronjobsIdIndexRoute,
}

const CronjobsIdRouteWithChildren = CronjobsIdRoute._addFileChildren(
  CronjobsIdRouteChildren,
)

interface CronjobsRouteChildren {
  CronjobsIdRoute: typeof CronjobsIdRouteWithChildren
  CronjobsNewRoute: typeof CronjobsNewRoute
  CronjobsIndexRoute: typeof CronjobsIndexRoute
}

const CronjobsRouteChildren: CronjobsRouteChildren = {
  CronjobsIdRoute: CronjobsIdRouteWithChildren,
  CronjobsNewRoute: CronjobsNewRoute,
  CronjobsIndexRoute: CronjobsIndexRoute,
}

const CronjobsRouteWithChildren = CronjobsRoute._addFileChildren(
  CronjobsRouteChildren,
)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsExtractFromUrlRoute: typeof JobsExtractFromUrlRoute
  JobsNewRoute: typeof JobsNewRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsExtractFromUrlRoute: JobsExtractFromUrlRoute,
  JobsNewRoute: JobsNewRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface KnowledgeBaseRouteChildren {
  KnowledgeBaseIndexRoute: typeof KnowledgeBaseIndexRoute
}

const KnowledgeBaseRouteChildren: KnowledgeBaseRouteChildren = {
  KnowledgeBaseIndexRoute: KnowledgeBaseIndexRoute,
}

const KnowledgeBaseRouteWithChildren = KnowledgeBaseRoute._addFileChildren(
  KnowledgeBaseRouteChildren,
)

interface MailRouteChildren {
  MailIndexRoute: typeof MailIndexRoute
}

const MailRouteChildren: MailRouteChildren = {
  MailIndexRoute: MailIndexRoute,
}

const MailRouteWithChildren = MailRoute._addFileChildren(MailRouteChildren)

interface ApiCronjobsIdRouteChildren {
  ApiCronjobsIdLogsRoute: typeof ApiCronjobsIdLogsRoute
  ApiCronjobsIdTestRoute: typeof ApiCronjobsIdTestRoute
}

const ApiCronjobsIdRouteChildren: ApiCronjobsIdRouteChildren = {
  ApiCronjobsIdLogsRoute: ApiCronjobsIdLogsRoute,
  ApiCronjobsIdTestRoute: ApiCronjobsIdTestRoute,
}

const ApiCronjobsIdRouteWithChildren = ApiCronjobsIdRoute._addFileChildren(
  ApiCronjobsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRouteWithChildren,
  CronjobsRoute: CronjobsRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  KnowledgeBaseRoute: KnowledgeBaseRouteWithChildren,
  MailRoute: MailRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiChatSyncRoute: ApiChatSyncRoute,
  ApiSectionsRoute: ApiSectionsRoute,
  ApiConversationsIdRoute: ApiConversationsIdRoute,
  ApiCronjobsIdRoute: ApiCronjobsIdRouteWithChildren,
  ApiFilesFilenameRoute: ApiFilesFilenameRoute,
  ApiGeneratedFilesIdRoute: ApiGeneratedFilesIdRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiJobsGenerateResumeRoute: ApiJobsGenerateResumeRoute,
  ApiJobsProcessRoute: ApiJobsProcessRoute,
  ApiKnowledgeBaseIdRoute: ApiKnowledgeBaseIdRoute,
  ApiMailIdRoute: ApiMailIdRoute,
  ApiMailAllRoute: ApiMailAllRoute,
  ApiMailEmailCountRoute: ApiMailEmailCountRoute,
  ApiMailEmailsRoute: ApiMailEmailsRoute,
  ApiMailEmailsByJobRoute: ApiMailEmailsByJobRoute,
  ApiMailIngestRoute: ApiMailIngestRoute,
  ApiMailStoreEmailsRoute: ApiMailStoreEmailsRoute,
  ApiReportsScrapeJobsRoute: ApiReportsScrapeJobsRoute,
  ApiConversationsIndexRoute: ApiConversationsIndexRoute,
  ApiCronjobsIndexRoute: ApiCronjobsIndexRoute,
  ApiGeneratedFilesIndexRoute: ApiGeneratedFilesIndexRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiKnowledgeBaseIndexRoute: ApiKnowledgeBaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
